-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 287,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {28.5 / 64, -17.5 / 64},
  ["sprite_count"] = 1,
  ["width"] = 265,
}
