-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 282,
  ["line_length"] = 12,
  ["lines_per_file"] = 11,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, 0 / 64},
  ["sprite_count"] = 128,
  ["width"] = 270,
}
