-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 261,
  ["line_length"] = 8,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {0.5 / 64, -14.5 / 64},
  ["sprite_count"] = 60,
  ["width"] = 251,
}
