-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 397,
  ["line_length"] = 8,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  -- Match base/emission crop offset: split-emission re-packs the already-cropped
  -- emission, so spritter resets shift to 0; restore the emission's shift so the
  -- glow registers with the body and the tier mask.
  ["shift"] = {-3 / 64, 1.5 / 64},
  ["sprite_count"] = 60,
  ["width"] = 394,
}
