-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 194,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["scale"] = 0.5,
  -- rebuild_mask.sh bakes the stencil onto the ALREADY-CROPPED base.png, so
  -- spritter measures this shift against the cropped base frame, not the
  -- original cell -- it loses the base's own crop offset and the tint renders
  -- shifted off the body. Correct shift = base shift (-3, 1.5) + spritter's
  -- recorded (-48.5, -37.5).
  ["shift"] = {-51.5 / 64, -36 / 64},
  ["sprite_count"] = 1,
  ["width"] = 279,
}
