-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 158,
  ["line_length"] = 9,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {-77 / 64, 63 / 64},
  ["sprite_count"] = 64,
  ["width"] = 124,
}
