-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 151,
  ["line_length"] = 7,
  ["lines_per_file"] = 10,
  ["scale"] = 0.5,
  ["shift"] = {0.5 / 64, 70.5 / 64},
  ["sprite_count"] = 64,
  ["width"] = 235,
}
