-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 310,
  ["line_length"] = 10,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {-3 / 64, 0 / 64},
  ["sprite_count"] = 80,
  ["width"] = 264,
}
