-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 259,
  ["line_length"] = 9,
  ["lines_per_file"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {7.5 / 64, -0.5 / 64},
  ["sprite_count"] = 60,
  ["width"] = 181,
}
